version: '3.1'
services:

  # The nginx Web Server
  web:
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    working_dir: /var/www
    ports:
      - 8080:80
    volumes:
      - ./:/var/www:cached
      - ./docker/configs/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./docker/configs/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - "app"
      - "database"

  # The PHP Application
  app:
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    working_dir: /var/www
    ports:
      - 6001:6001
    environment:
      # dev database
      DB_HOST: database
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./:/var/www:cached
      - ./docker/configs/php/php.ini:/usr/local/etc/php/conf.d/php.ini:cached
    depends_on:
      - "database"

  # The Database
  database:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: laracasts
      MYSQL_USER: laracasts
      MYSQL_PASSWORD: laracasts
      MYSQL_ROOT_PASSWORD: laracasts
    volumes:
        - ./docker/configs/mariadb/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306

  # Redis
  redis:
    image: redis
    ports:
      - 6379:6379